name: build

on:
  push:
    branches:
      - 'dev'

env:
  DOCKERHUB_USERNAME: jheyuliu

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      #- name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ env.DOCKERHUB_USERNAME }}
      #   password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Build Docker Image'
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/tiny-url-app:${{ steps.vars.outputs.sha_short }}
          docker push ghcr.io/${{ github.actor }}/tiny-url-app:${{ steps.vars.outputs.sha_short }}
      #- name: Build backend and push
      #  uses: docker/build-push-action@v3
      #  with:
      #    push: true
      #    platforms: linux/amd64,linux/arm64
      #    tags: ${{ env.DOCKERHUB_USERNAME }}/${{ steps.vars.outputs.sha_short }}